steps:
  - id: 'install app packages'
    name: node:14
    entrypoint: npm
    dir: app
    args: ['ci']

  - id: 'build'
    name: node:14
    entrypoint: npm
    dir: app
    args: ['run', 'build']
    env:
      - 'COMMIT_ID=$SHORT_SHA'
      - 'BRANCH_NAME=$BRANCH_NAME'

  - id: 'deploy'
    name: gcr.io/$PROJECT_ID/firebase
    dir: app
    args: ['deploy', '--project', '$PROJECT_ID']
